# CRAGR_v2
# r_path:
# cragr_script:
# samples:
# chroms:
# genome:
# chrom_sizes:
# output_dir:
# seed:
# exclude_regions:
# high_mappability:
# gc_correct:
# gc_correct_method:
# gc_correct_N:
# fdr_threshold:
# merge_gap
# idr_threshold:
# min_mapq:
# min_fraglen:
# max_fraglen:
# window_size:
# step_size: