# CRAGR_v2
r_script: "NONE"
samples: "/projects/b1198/epifluidlab/ravi/0217/samples.txt"
chroms: "/projects/b1198/epifluidlab/ravi/0217/hg38.chrom.sizes"
genome: "hg38"
chrom_sizes: "/projects/b1198/epifluidlab/ravi/0217/chroms.txt"
output_dir: "path/to/output_directory"
# seed:
# exclude_regions:
# high_mappability:
# gc_correct:
# gc_correct_method:
# gc_correct_N:
# idr_threshold:
# min_mapq:
# min_fraglen:
# max_fraglen:
# window_size:
# step_size: